blank_issues_enabled: false
contact_links:
  - name: Contribute guide
    url: https://www.reactiveui.net/contribute/index.html
    about: Please read this before opening an issue or PR.
  - name: Questions & Discussions
    url: https://github.com/reactiveui/ReactiveUI/discussions
    about: For general questions about ReactiveUI, ask in GitHub Discussions.
  - name: Chat
    url: https://www.reactiveui.net/slack
    about: Our Slack chat community invite.
