name: 'Lock Threads'

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write
  discussions: write

concurrency:
  group: lock-threads

jobs:
  lock:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v5
        with:
          issue-inactive-days: '90'
          pr-inactive-days: '90'
          issue-lock-reason: 'resolved'
          pr-lock-reason: 'resolved'
          exclude-issue-created-before: ''
          exclude-any-issue-labels: 'help-wanted'
          add-issue-labels: 'outdated'
